### ISSUE TITLE
Написать функционал расчёта MACCS

### ISSUE THREAD

**Issue by bugor40** [DariGD/ai24-toxicity-prediction#17]
## Что хотим?
Хотим описать молекулы какими-то признаками. В данной задаче хотим чтобы это признаки были MACCS

MACCS - это стандартизированный набор флагов, по которым на заре развития БД пользовались химики для поиска в химических базах данных.
Пример:
- в молекуле есть связь S-S
- в молекуле есть NO 
- и тд

## Необходимо

Написать функционал, который позволит переводить SMILES в MACCS. В результате в main есть функция, которой можно расчитывать MACCS

**Полезные ссылки**
- [библиотека RDKit](https://rdkit.org/)
- [MACCS](https://rdkit.org/docs/GettingStartedInPython.html#maccs-keys)

**Comment by DariGD** [comment]
MACCS (Molecular ACCess System) ключи представляют собой набор бинарных дескрипторов, которые описывают наличие или отсутствие определенных структурных признаков в молекуле. Полный набор MACCS-кодов содержит 166 различных битов, и каждый из них анализирует специфический элемент структуры молекулы. 

Подробнее о признаках, за которые отвечает каждый бит в наборе MACCS ключей можно найти по ссылке ниже
http://www.mayachemtools.org/docs/scripts/html/MACCSKeysFingerprints.htm

С помощью открытой библиотеки RDkit возможно реализовать получение отпечатка MACCS из Smiles. При этом RDkit создает битовый отпечаток, используя 167 структурных паттернов, тогда как стандартная интерпретация MACCS ключей основана на 166-битной последовательности. RDKit сохраняет номера ключей MACCS, поэтому ставит нулевой бит в начале строки. Чтобы вычленить в стандартном виде MACCS Key достаточно просто проигнорировать первый бит.


На текущий момент реализован функционал перевода с помощью библиотеки RDkit Smiles в MACCS
```
!pip install rdkit
from rdkit import Chem
from rdkit.Chem import MACCSkeys
def maccs(smile):
  mol = Chem.MolFromSmiles(smile)
  maccs_keys = MACCSkeys.GenMACCSKeys(mol)
  n = maccs_keys.ToBitString()
  p = n[1:]
  return p
```

Далее возможно реализовать функцию связывания каждого бита с его химическим смыслом
